# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1527053263);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1527053383);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1527115259);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1527053143);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1527053623);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1527107939);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1527053743);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1527053503);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1527052873);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 59);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e5b44a7d-1040-40e4-8887-462a341ed77e}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1527012000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1527112430);
user_pref("browser.onboarding.notification.prompt-count", 5);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1527114700223");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1527116472223");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1527115173837");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1527118773837");
user_pref("browser.search.countryCode", "KZ");
user_pref("browser.search.region", "KZ");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1527052905");
user_pref("browser.slowStartup.averageTime", 10633);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180208174847");
user_pref("browser.startup.homepage_override.mstone", "58.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":13,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1527052897394");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "58.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "db540e16b84e4e57b0fde8eaccd4e296");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.getAddons.cache.lastUpdate", 1527053269);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "58.0.2");
user_pref("extensions.lastPlatformVersion", "58.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.user_id", "fbaf7ac5-9ed4-4d72-8133-eba63ea887fe");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"e86eb55d-5414-4ca4-9637-fafc6d751028\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1527055606);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1527052988);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180208174847");
user_pref("media.gmp-manager.lastCheck", 1527052986);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1527055607);
user_pref("places.history.expiration.transient_current_max_pages", 79656);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1527018099);
user_pref("services.blocklist.clock_skew_seconds", 35285);
user_pref("services.blocklist.gfx.checked", 1527018099);
user_pref("services.blocklist.last_etag", "\"1526508284121\"");
user_pref("services.blocklist.last_update_seconds", 1527018099);
user_pref("services.blocklist.onecrl.checked", 1527018099);
user_pref("services.blocklist.pinning.checked", 1527018099);
user_pref("services.blocklist.plugins.checked", 1527018099);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1527055606);
user_pref("toolkit.startup.last_success", 1527052868);
user_pref("toolkit.telemetry.cachedClientID", "3c256c24-fc38-4911-a707-6e6a6c54f65b");
user_pref("toolkit.telemetry.previousBuildID", "20180208174847");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
